# Generated by Django 5.2.4 on 2026-04-21 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(unique=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meses_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de Mes',
                'verbose_name_plural': 'Control de Meses',
                'ordering': ['mes'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('DIRECTOR', 'Director')], default='FUNCIONARIO', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='TrasladoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_reporte', models.TimeField()),
                ('hora_egreso', models.TimeField(blank=True, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=100)),
                ('quien_reporta', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('procedimiento', models.CharField(max_length=255)),
                ('medico', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=100)),
                ('radio_operador', models.CharField(max_length=100)),
                ('ambulancia', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, default='')),
                ('mes', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Traslado de Paciente',
                'verbose_name_plural': 'Traslados de Pacientes',
                'ordering': ['fecha', 'hora_reporte'],
                'indexes': [models.Index(fields=['mes'], name='app_traslad_mes_3ad501_idx'), models.Index(fields=['fecha'], name='app_traslad_fecha_2aacc9_idx')],
            },
        ),
    ]
